import 'package:flutter/material.dart';
import 'package:coffeeshop_app/coffee_item.dart';

List<String> categories = [
  'All',
  'Coffee',
  'Tea',
  'Juice',
  'Water',
  'Pastries',
  'Cold Brew',
  'Desserts',
];

Map<String, CoffeeItem> coffeeMap = {
  "1": CoffeeItem(
    title: "Latte",
    description: "Rich and warm",
    price: 17.50,
    icon: Icons.coffee_sharp,
    category: "Coffee",
  ),
  "2": CoffeeItem(
    title: "Espresso",
    description: "Strong and dark",
    price: 12.00,
    icon: Icons.local_cafe,
    category: "Coffee",
  ),
  "3": CoffeeItem(
    title: "Green tea",
    description: "Light and clean",
    price: 15.50,
    icon: Icons.coffee_sharp,
    category: "Tea",
  ),
  "4": CoffeeItem(
    title: "Orange Juice",
    description: "Fresh pressed",
    price: 20.0,
    icon: Icons.coffee,
    category: "Juice",
  ),
  "5": CoffeeItem(
    title: "Cappuccino",
    description: "Foam on top",
    price: 18.0,
    icon: Icons.coffee_sharp,
    category: "Coffee",
  ),
  "6": CoffeeItem(
    title: "Mint tea",
    description: "Cool finish",
    price: 14.0,
    icon: Icons.coffee,
    category: "Tea",
  ),
  "7": CoffeeItem(
    title: "Spanish Latte",
    description: "Espresso with sweetened condensed milk",
    price: 15.0,
    icon: Icons.coffee,
    category: "Coffee",
  ),
  "8": CoffeeItem(
    title: "Hazelnut Macchiato",
    description: "Espresso, steamed milk & hazelnut syrup",
    price: 17.0,
    icon: Icons.coffee,
    category: "Coffee",
  ),
  "9": CoffeeItem(
    title: "Croissant",
    description: "Butter flaky pastry",
    price: 10.0,
    icon: Icons.bakery_dining,
    category: "Pastries",
  ),
  "10": CoffeeItem(
    title: "Vanilla Cold Brew",
    description: "Slow-steeped coffee with vanilla",
    price: 19.0,
    icon: Icons.ac_unit,
    category: "Cold Brew",
  ),
  "11": CoffeeItem(
    title: "Tiramisu",
    description: "Classic Italian coffee cake",
    price: 22.0,
    icon: Icons.cake,
    category: "Desserts",
  ),
  "12": CoffeeItem(
    title: "Mineral Water",
    description: "Pure refreshing water",
    price: 5.0,
    icon: Icons.water_drop,
    category: "Water",
  ),
  "13": CoffeeItem(
    title: "Blueberry Muffin",
    description: "Freshly baked blueberry muffin",
    price: 12.5,
    icon: Icons.bakery_dining,
    category: "Pastries",
  ),
  "14": CoffeeItem(
    title: "Iced Peach Tea",
    description: "Brewed black tea with peach flavor",
    price: 16.0,
    icon: Icons.coffee_sharp,
    category: "Tea",
  ),
  "15": CoffeeItem(
    title: "Nitro Cold Brew",
    description: "Infused with nitrogen for velvety smooth taste",
    price: 21.0,
    icon: Icons.ac_unit,
    category: "Cold Brew",
  ),
  "16": CoffeeItem(
    title: "Sparkling Water",
    description: "Carbonated refreshing water",
    price: 7.0,
    icon: Icons.water_drop,
    category: "Water",
  ),
  "17": CoffeeItem(
    title: "Cheesecake",
    description: "Rich creamy strawberry cheesecake",
    price: 25.0,
    icon: Icons.cake,
    category: "Desserts",
  ),
  "18": CoffeeItem(
    title: "Watermelon Juice",
    description: "Sweet fresh blended watermelon",
    price: 18.5,
    icon: Icons.coffee,
    category: "Juice",
  ),
};
